# Generated by Django 5.2.7 on 2025-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="ususario",
            new_name="usuario",
        ),
    ]
