# Generated by Django 4.2 on 2025-11-12 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('tipo_mascota', models.CharField(max_length=50, verbose_name='Tipo de Mascota')),
                ('tipo_servicio', models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('estetica', 'Estética'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía')], default='consulta', max_length=20)),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la cita')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del problema')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
    ]
