# Generated by Django 5.2.7 on 2025-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código del producto",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del producto"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio del producto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        max_length=300, verbose_name="Descripcion del producto"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Cantidad")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen del producto",
                    ),
                ),
            ],
        ),
    ]
