# Generated by Django 6.0 on 2025-12-15 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100, verbose_name='Nombre de la vacuna')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de aplicación')),
                ('proxima_dosis', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Número de lote')),
                ('veterinario_aplico', models.CharField(max_length=100, verbose_name='Veterinario que aplicó')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de consulta')),
                ('tipo_consulta', models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('estetica', 'Estética'), ('urgencia', 'Urgencia'), ('cirugia', 'Cirugía'), ('control', 'Control'), ('emergencia', 'Emergencia')], max_length=20, verbose_name='Tipo de consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnostico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento prescrito')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos administrados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('estado_salud', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('grave', 'Grave'), ('critico', 'Crítico')], default='bueno', max_length=20, verbose_name='Estado de salud')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Proxima cita recomendada')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_urgente', models.BooleanField(default=False, verbose_name='Caso urgente')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita', verbose_name='Cita relacionada')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-fecha_consulta', '-creado_en'],
                'permissions': [('puede_ver_historial', 'Puede ver historiales médicos'), ('puede_editar_historial', 'Puede editar historiales médicos')],
            },
        ),
    ]
