# Generated by Django 6.0 on 2025-12-15 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historialM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_veterinario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='historialM.historialmedico'),
        ),
    ]
